spring:
  application:
    name: service_with_observability

management:
  endpoints:
    web:
      exposure:
        include: metrics, health
  metrics:
    export:
      otlp:
        enabled: true
        uri: http://localhost:4318/v1/metrics
        step: 10s